import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="w-full">
          <h1 className=" font-extrabold text-xl tracking-wide">
            Supa Smoothies
          </h1>
          <Link href="/" className="underline">
            Home
          </Link>
          <Link href="/create" className="underline">
            Create New Smoothie
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
